<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MedicineSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('medicines')->insert([
            [
                'id' => 'R34T9',
                'name' => 'Paracetamol',
                'usage' => 'thuốc giảm đau hạ sốt',
                'unit' => 'Viên',
                'expiry_date' => Carbon::createFromFormat('d-m-Y', '18-05-2025'),
                'price' => 159000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '5G89E',
                'name' => 'Amoxicillin',
                'usage' => 'kháng sinh đối với nhiều bệnh khác nhau',
                'unit' => 'Hủ',
                'expiry_date' => Carbon::createFromFormat('d-m-Y', '08-04-2025'),
                'price' => 250000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'Z9H4A',
                'name' => 'Aspirin',
                'usage' => 'thuốc giảm đau và chống viêm',
                'unit' => 'Viên',
                'expiry_date' => Carbon::createFromFormat('d-m-Y', '27-03-2025'),
                'price' => 220000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7J6L8',
                'name' => 'Ibuprofen',
                'usage' => 'thuốc giảm đau giảm viêm và hạ sốt',
                'unit' => 'Vỉ',
                'expiry_date' => Carbon::createFromFormat('d-m-Y', '12-02-2025'),
                'price' => 178000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'K2N1S',
                'name' => 'Metformin',
                'usage' => 'thuốc điều trị tiểu đường',
                'unit' => 'Gói',
                'expiry_date' => Carbon::createFromFormat('d-m-Y', '21-01-2025'),
                'price' => 640000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3M6R7',
                'name' => 'Omeprazole',
                'usage' => 'thuốc ức chế bài tiết axit dạ dày',
                'unit' => 'Viên',
                'expiry_date' => Carbon::createFromFormat('d-m-Y', '03-12-2024'),
                'price' => 992000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'P1K8L',
                'name' => 'Simvastatin',
                'usage' => 'thuốc giảm cholesterol và nguy cơ bệnh tim mạch',
                'unit' => 'Hủ',
                'expiry_date' => Carbon::createFromFormat('d-m-Y', '19-11-2024'),
                'price' => 129000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '9B2T6',
                'name' => 'Cephalexin',
                'usage' => 'kháng sinh đối với nhiều bệnh lý khác nhau',
                'unit' => 'Gói',
                'expiry_date' => Carbon::createFromFormat('d-m-Y', '16-10-2024'),
                'price' => 670000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'L3V8F',
                'name' => 'Prednisone',
                'usage' => 'thuốc chống viêm, giảm phản ứng miễn dịch',
                'unit' => 'Ml',
                'expiry_date' => Carbon::createFromFormat('d-m-Y', '28-09-2024'),
                'price' => 453000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '4G7S2',
                'name' => 'Furosemide',
                'usage' => 'thuốc giảm đau tim và huyết áp',
                'unit' => 'Vien',
                'expiry_date' => Carbon::createFromFormat('d-m-Y', '05-08-2024'),
                'price' => 674000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'R36D4',
                'name' => 'Diphenhydramine',
                'usage' => 'thuốc giảm ngứa và dị ứng',
                'unit' => 'Viên',
                'expiry_date' => Carbon::createFromFormat('d-m-Y', '11-07-2024'),
                'price' => 764000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'D0G43',
                'name' => 'Insulin',
                'usage' => 'thuốc điều trị tiểu đường',
                'unit' => 'Gói',
                'expiry_date' => Carbon::createFromFormat('d-m-Y', '22-06-2024'),
                'price' => 367000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'EX91T',
                'name' => 'Amlodipine',
                'usage' => 'thuốc hạ huyết áp',
                'unit' => 'Gói',
                'expiry_date' => Carbon::createFromFormat('d-m-Y', '07-05-2024'),
                'price' => 12900000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'L91Q8',
                'name' => 'Levothyroxine',
                'usage' => 'thuốc điều trị rối loạn chức năng tuyến giáp',
                'unit' => 'Hủ',
                'expiry_date' => Carbon::createFromFormat('d-m-Y', '15-03-2024'),
                'price' => 1328000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'L0YJ9',
                'name' => 'Warfarin',
                'usage' => 'thuốc chống đông máu',
                'unit' => 'Viên',
                'expiry_date' => Carbon::createFromFormat('d-m-Y', '01-02-2024'),
                'price' => 1499000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
